name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-win:
    runs-on: [windows-latest]
    env:
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install requests
      run: pip install requests
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  build-macos:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install sdl
      run: brew install sdl2
    - name: Install sdl2_ttf
      run: brew install sdl2_ttf
    - name: Install updated ncurses
      run: brew install ncurses
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-ubuntu:
    runs-on: [ubuntu-latest]
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Update
      run: sudo apt-get update -y
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev -y
    - name: Install SDL2ttf
      run: sudo apt-get install libsdl2-ttf-dev -y
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
